/* eslint-disable react/no-unescaped-entities */
import Head from 'next/head'
import { Inter } from '@next/font/google'
import TopArea from '../components/TopArea';
import StudentCard from '../components/StudentCard';
import { useSession } from 'next-auth/react';
import Students from '../components/Students';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { status, data } = useSession({ required: true }) as any;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TopArea />
      <main style={{
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
      }}>
        {
          status === 'authenticated' && (<Students />)
        }
      </main>

    </>
  )
}
